export interface NoteMetadata {
  title?: string;
  date?: string;
  tags?: string[];
  [key: string]: any;
}

export interface NoteItem {
  id: string; // usually the file path
  path: string;
  name: string;
  type: "file";
  content?: string; // Markdown content
  metadata?: NoteMetadata;
  sha?: string; // GitHub blob SHA
}

export interface FolderItem {
  id: string;
  path: string;
  name: string;
  type: "folder";
  children: (NoteItem | FolderItem)[];
}

export type FileSystemNode = NoteItem | FolderItem;

// The raw data format generated by the build script
export interface RawNoteFile {
  filePath: string;
  content?: string;
  metadata?: NoteMetadata;
  sha?: string;
  blobUrl?: string;
}

export interface OutlineItem {
  id: string;
  text: string;
  level: number;
  line: number;
  children: OutlineItem[];
}
