import React, { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import rehypeHighlight from "rehype-highlight";

interface MarkdownRendererProps {
  content: string;
}

// --- Icons ---
const CopyIcon = () => (
  <svg
    className="w-4 h-4"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
    />
  </svg>
);

const CheckIcon = () => (
  <svg
    className="w-4 h-4 text-green-500"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M5 13l4 4L19 7"
    />
  </svg>
);

const ChevronDownIcon = ({ collapsed }: { collapsed: boolean }) => (
  <svg
    className={`w-4 h-4 transition-transform duration-200 ${collapsed ? "-rotate-90" : "rotate-0"}`}
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M19 9l-7 7-7-7"
    />
  </svg>
);

// --- Custom Pre Block Component ---
// This wraps the <pre> tag generated by react-markdown
const PreBlock = ({ children }: { children: React.ReactNode }) => {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [isCopied, setIsCopied] = useState(false);

  // Extract language from className if present on the nested <code> element
  // children is usually a "code" react element
  let language = "Code";
  let codeText = "";

  if (React.isValidElement(children)) {
    const props = children.props as any;
    // Highlight.js via rehype-highlight might add "language-xyz" class
    if (props.className) {
      const match = /language-(\w+)/.exec(props.className || "");
      if (match) language = match[1];
    }
    // Extract raw text for copying
    if (typeof props.children === "string") {
      codeText = props.children;
    } else if (Array.isArray(props.children)) {
      codeText = props.children
        .map((c: any) => (typeof c === "string" ? c : ""))
        .join("");
    }
  }

  const handleCopy = (e: React.MouseEvent) => {
    e.stopPropagation();
    navigator.clipboard.writeText(codeText).then(() => {
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 3000);
    });
  };

  return (
    <div className="my-6 rounded-lg overflow-hidden border border-zinc-200 dark:border-zinc-800 bg-[#0d1117] shadow-sm">
      {/* Code Header */}
      <div
        className="flex items-center justify-between px-4 py-2 bg-zinc-100 dark:bg-[#161b22] border-b border-zinc-200 dark:border-zinc-800 select-none cursor-pointer"
        onClick={() => setIsCollapsed(!isCollapsed)}
      >
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">
            {language}
          </span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2 py-1 rounded text-xs text-zinc-500 hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-800 transition-all active:scale-95"
            title="Copy code"
          >
            {isCopied ? <CheckIcon /> : <CopyIcon />}
            <span>{isCopied ? "Copied!" : "Copy"}</span>
          </button>
          <button
            className="p-1 text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 transition-colors"
            title={isCollapsed ? "Expand" : "Collapse"}
          >
            <ChevronDownIcon collapsed={isCollapsed} />
          </button>
        </div>
      </div>

      {/* Code Content */}
      <div
        className={`transition-all duration-300 ease-in-out ${isCollapsed ? "max-h-0 opacity-0" : "max-h-[2000px] opacity-100"}`}
      >
        <div className="relative overflow-x-auto">
          {/* We use a span wrapper to apply the pre styles without nesting another pre */}
          <pre className="!m-0 !p-4 !bg-transparent !border-none custom-scrollbar">
            {children}
          </pre>
        </div>
      </div>
    </div>
  );
};

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({
  content,
}) => {
  return (
    // Updated colors to Zinc (black-gray)
    <div className="prose prose-zinc dark:prose-invert max-w-none prose-headings:font-semibold prose-a:text-blue-600 dark:prose-a:text-blue-400 prose-pre:m-0 prose-pre:p-0 prose-pre:bg-transparent p-8 bg-white dark:bg-zinc-950 shadow-sm min-h-screen transition-colors duration-200">
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkMath]}
        rehypePlugins={[rehypeKatex, rehypeHighlight]}
        components={{
          pre: PreBlock,
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
};
