import React, { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus, vs } from "react-syntax-highlighter/dist/esm/styles/prism";
import "github-markdown-css/github-markdown-light.css";

interface MarkdownRendererProps {
  content: string;
  isDark?: boolean;
  variant?: "document" | "chat";
  onSelectionAction?: (text: string) => void;
}

// --- Icons ---
const SparklesIcon = () => (
  <svg
    className="w-4 h-4"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
    />
  </svg>
);

const CopyIcon = () => (
  <svg
    className="w-4 h-4"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
    />
  </svg>
);

const CheckIcon = () => (
  <svg
    className="w-4 h-4 text-green-500"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M5 13l4 4L19 7"
    />
  </svg>
);

const ChevronDownIcon = ({ collapsed }: { collapsed: boolean }) => (
  <svg
    className={`w-4 h-4 transition-transform duration-200 ${collapsed ? "-rotate-90" : "rotate-0"}`}
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M19 9l-7 7-7-7"
    />
  </svg>
);

// --- Custom Pre Block Component ---
// This wraps the <pre> tag generated by react-markdown
const PreBlock = ({ children, isDark }: { children: React.ReactNode; isDark: boolean }) => {
  const { t } = useTranslation();
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [isCopied, setIsCopied] = useState(false);

  // Extract language from className if present on the nested <code> element
  // children is usually a "code" react element
  let language = "text";
  let codeText = "";

  if (React.isValidElement(children)) {
    const props = children.props as any;
    // Extract language from className (e.g., "language-typescript")
    if (props.className) {
      const match = /language-(\w+)/.exec(props.className || "");
      if (match) language = match[1];
    }
    // Extract raw text for copying
    if (typeof props.children === "string") {
      codeText = props.children;
    } else if (Array.isArray(props.children)) {
      codeText = props.children
        .map((c: any) => (typeof c === "string" ? c : ""))
        .join("");
    }
  }

  const handleCopy = (e: React.MouseEvent) => {
    e.stopPropagation();
    navigator.clipboard.writeText(codeText).then(() => {
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 3000);
    });
  };

  const customStyle = {
    margin: 0,
    padding: "1rem",
    background: "transparent",
    fontSize: "0.875rem",
    lineHeight: "1.5",
  };

  return (
    <div className="my-6 rounded-lg overflow-hidden border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-[#0d1117] shadow-sm max-w-full">
      {/* Code Header */}
      <div
        className="flex items-center justify-between px-4 py-2 bg-zinc-100 dark:bg-[#161b22] border-b border-zinc-200 dark:border-zinc-800 select-none cursor-pointer"
        onClick={() => setIsCollapsed(!isCollapsed)}
      >
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">
            {language}
          </span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2 py-1 rounded text-xs text-zinc-500 hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-800 transition-all active:scale-95"
            title={t('markdown.copyCode')}
          >
            {isCopied ? <CheckIcon /> : <CopyIcon />}
            <span>{isCopied ? t('markdown.copied') : t('markdown.copy')}</span>
          </button>
          <button
            className="p-1 text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 transition-colors"
            title={isCollapsed ? t('markdown.expand') : t('markdown.collapse')}
          >
            <ChevronDownIcon collapsed={isCollapsed} />
          </button>
        </div>
      </div>

      {/* Code Content */}
      <div
        className={`transition-all duration-300 ease-in-out ${isCollapsed ? "max-h-0 opacity-0" : "max-h-[2000px] opacity-100"}`}
      >
        <div className="relative w-full">
          <SyntaxHighlighter
            language={language}
            style={isDark ? vscDarkPlus : vs}
            customStyle={customStyle}
            wrapLines={true}
            PreTag="div"
            CodeTag="div"
          >
            {codeText}
          </SyntaxHighlighter>
        </div>
      </div>
    </div>
  );
};

// --- Thinking Block Component ---
const ThinkingBlock = ({ content, isDark }: { content: string; isDark: boolean }) => {
  const { t } = useTranslation();
  const [isCollapsed, setIsCollapsed] = useState(false);

  return (
    <div className="my-3 border border-zinc-200 dark:border-zinc-800 rounded-lg overflow-hidden bg-zinc-50 dark:bg-zinc-900/50">
      <button
        onClick={() => setIsCollapsed(!isCollapsed)}
        className="flex items-center gap-2 w-full px-3 py-2 text-xs font-medium text-zinc-600 dark:text-zinc-400 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors text-left select-none"
      >
        <SparklesIcon />
        <span className="flex-1">{t('copilot.thinkingProcess')}</span>
        <ChevronDownIcon collapsed={isCollapsed} />
      </button>
      
      <div
        className={`transition-all duration-300 ease-in-out px-3 text-sm text-zinc-600 dark:text-zinc-400 font-mono overflow-hidden ${
          isCollapsed ? "max-h-0 opacity-0" : "max-h-[500px] opacity-100 py-3 border-t border-zinc-200 dark:border-zinc-800 overflow-y-auto"
        }`}
      >
        <div className="whitespace-pre-wrap opacity-80">{content}</div>
      </div>
    </div>
  );
};

// --- Heading Helper ---
const slugify = (text: string) => {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s\u4e00-\u9fa5-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
};

const getNodeText = (node: any): string => {
  if (node == null) return "";
  if (['string', 'number'].includes(typeof node)) return node.toString();
  if (node instanceof Array) return node.map(getNodeText).join('');
  if (typeof node === 'object' && node.props) return getNodeText(node.props.children);
  return "";
};

const Heading = ({ level, children, ...props }: any) => {
  const Tag = `h${level}` as keyof JSX.IntrinsicElements;
  const text = getNodeText(children);
  const id = slugify(text);
  return <Tag id={id} {...props}>{children}</Tag>;
};

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({
  content,
  isDark = false,
  variant = "document",
  onSelectionAction,
}) => {
  const { t } = useTranslation();
  const containerClasses = variant === "document"
    ? "markdown-body p-8 bg-white dark:bg-zinc-950 min-h-screen transition-colors duration-200 text-zinc-900 dark:text-zinc-100 relative"
    : "markdown-body bg-transparent text-zinc-800 dark:text-zinc-200 text-sm"; // Chat variant

  const [selectionMenu, setSelectionMenu] = useState<{ x: number; y: number; text: string } | null>(null);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
        const target = e.target as HTMLElement;
        if (target.closest('#fia-copilot-selection-btn')) return;
        setSelectionMenu(null);
    };
    
    if (selectionMenu) {
        document.addEventListener('mousedown', handleClickOutside);
    }
    return () => {
        document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [selectionMenu]);

  const handleMouseUp = () => {
      if (!onSelectionAction || variant !== "document") return;
      
      const selection = window.getSelection();
      if (!selection || selection.isCollapsed) {
          return; 
      }
      
      const text = selection.toString().trim();
      if (!text) return;
      
      const range = selection.getRangeAt(0);
      const rect = range.getBoundingClientRect();
      
      setSelectionMenu({
          x: rect.left + rect.width / 2,
          y: rect.top - 8,
          text: text
      });
  };

  // Split content by <think> tags
  // Regex matches <think> content </think>
  // Also handle unclosed <think> tag if streaming
  const parts = content.split(/(<think>[\s\S]*?<\/think>|<think>[\s\S]*)/g);

  return (
    // Updated colors to Zinc (black-gray)
    // Removed 'prose' (Tailwind Typography) and added 'markdown-body' (GitHub Markdown CSS)
    <div className={containerClasses} onMouseUp={handleMouseUp}>
      <style>{`
        .markdown-body {
          background-color: transparent !important;
          font-family: inherit;
          min-height: auto !important;
        }
        
        /* Ensure PreBlock scrolls horizontally */
        .markdown-body pre {
            white-space: pre;
            overflow-x: auto;
            background-color: transparent !important;
            border: none !important;
            padding: 0 !important;
            margin: 0 !important;
        }

        /* Dark mode overrides for markdown-body */
        .dark .markdown-body {
          color-scheme: dark;
          color: #e4e4e7; /* zinc-200 */
        }

        .dark .markdown-body h1,
        .dark .markdown-body h2,
        .dark .markdown-body h3,
        .dark .markdown-body h4,
        .dark .markdown-body h5,
        .dark .markdown-body h6 {
          color: #f4f4f5; /* zinc-100 */
          border-bottom-color: #3f3f46; /* zinc-700 */
        }

        .dark .markdown-body a {
          color: #60a5fa; /* blue-400 */
        }
        
        .dark .markdown-body blockquote {
          color: #a1a1aa; /* zinc-400 */
          border-left-color: #3f3f46;
        }
        
        .dark .markdown-body hr {
          background-color: #3f3f46;
          height: 1px;
        }
        
        /* Table overrides */
        .dark .markdown-body table tr {
          background-color: transparent;
          border-color: #3f3f46;
        }
        .dark .markdown-body table tr:nth-child(2n) {
          background-color: rgba(63, 63, 70, 0.2);
        }
        .dark .markdown-body table th,
        .dark .markdown-body table td {
          border-color: #3f3f46;
        }
        
        /* Inline code override */
        .dark .markdown-body code:not([class*="language-"]) {
          background-color: rgba(63, 63, 70, 0.4);
          color: #e4e4e7;
        }

        /* Scrollbar styles for dark mode */
        .dark ::-webkit-scrollbar {
          width: 8px;
          height: 8px;
        }
        .dark ::-webkit-scrollbar-track {
          background: #18181b;
        }
        .dark ::-webkit-scrollbar-thumb {
          background: #3f3f46;
          border-radius: 4px;
        }
        .dark ::-webkit-scrollbar-thumb:hover {
          background: #52525b;
        }
      `}</style>

      {parts.map((part, index) => {
        if (part.startsWith("<think>")) {
          // Extract content
          let inner = part.replace("<think>", "");
          if (inner.endsWith("</think>")) {
            inner = inner.slice(0, -8);
          }
          return <ThinkingBlock key={index} content={inner} isDark={isDark} />;
        }
        
        if (!part) return null;

        return (
          <ReactMarkdown
            key={index}
            remarkPlugins={[remarkGfm, remarkMath]}
            rehypePlugins={[rehypeKatex]}
            components={{
              code: ({ className, children, ...props }: any) => {
                const match = /language-(\w+)/.exec(className || "");
                const isInline = !match && !String(children).includes("\n");
                
                if (isInline) {
                   return (
                     <code className={className} {...props}>
                       {children}
                     </code>
                   )
                }
                
                return (
                  <PreBlock isDark={isDark}>
                     <code className={className} {...props}>
                       {children}
                     </code>
                  </PreBlock>
                );
              },
              pre: ({ children }: any) => <>{children}</>,
              h1: (props) => <Heading level={1} {...props} />,
              h2: (props) => <Heading level={2} {...props} />,
              h3: (props) => <Heading level={3} {...props} />,
              h4: (props) => <Heading level={4} {...props} />,
              h5: (props) => <Heading level={5} {...props} />,
              h6: (props) => <Heading level={6} {...props} />,
              a: ({ node, ...props }: any) => (
                <a target="_blank" rel="noopener noreferrer" {...props} />
              ),
            }}
          >
            {part}
          </ReactMarkdown>
        );
      })}

      {selectionMenu && (
        <button
          id="fia-copilot-selection-btn"
          onClick={(e) => {
              e.stopPropagation();
              onSelectionAction && onSelectionAction(selectionMenu.text);
              setSelectionMenu(null);
              window.getSelection()?.removeAllRanges();
          }}
          className="fixed z-50 flex items-center gap-2 px-3 py-1.5 bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 rounded-full shadow-lg hover:scale-105 transition-transform animate-in fade-in zoom-in duration-200 cursor-pointer"
          style={{
              left: selectionMenu.x,
              top: selectionMenu.y,
              transform: 'translate(-50%, -100%)'
          }}
        >
          <SparklesIcon />
          <span className="text-xs font-semibold whitespace-nowrap">{t('app.askCopilot')}</span>
        </button>
      )}
    </div>
  );
};
