import React, { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus, vs } from "react-syntax-highlighter/dist/esm/styles/prism";
import "github-markdown-css/github-markdown-light.css";

interface MarkdownRendererProps {
  content: string;
  isDark?: boolean;
}

// --- Icons ---
const CopyIcon = () => (
  <svg
    className="w-4 h-4"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
    />
  </svg>
);

const CheckIcon = () => (
  <svg
    className="w-4 h-4 text-green-500"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M5 13l4 4L19 7"
    />
  </svg>
);

const ChevronDownIcon = ({ collapsed }: { collapsed: boolean }) => (
  <svg
    className={`w-4 h-4 transition-transform duration-200 ${collapsed ? "-rotate-90" : "rotate-0"}`}
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M19 9l-7 7-7-7"
    />
  </svg>
);

// --- Custom Pre Block Component ---
// This wraps the <pre> tag generated by react-markdown
const PreBlock = ({ children, isDark }: { children: React.ReactNode; isDark: boolean }) => {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [isCopied, setIsCopied] = useState(false);

  // Extract language from className if present on the nested <code> element
  // children is usually a "code" react element
  let language = "text";
  let codeText = "";

  if (React.isValidElement(children)) {
    const props = children.props as any;
    // Extract language from className (e.g., "language-typescript")
    if (props.className) {
      const match = /language-(\w+)/.exec(props.className || "");
      if (match) language = match[1];
    }
    // Extract raw text for copying
    if (typeof props.children === "string") {
      codeText = props.children;
    } else if (Array.isArray(props.children)) {
      codeText = props.children
        .map((c: any) => (typeof c === "string" ? c : ""))
        .join("");
    }
  }

  const handleCopy = (e: React.MouseEvent) => {
    e.stopPropagation();
    navigator.clipboard.writeText(codeText).then(() => {
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 3000);
    });
  };

  const customStyle = {
    margin: 0,
    padding: "1rem",
    background: "transparent",
    fontSize: "0.875rem",
    lineHeight: "1.5",
  };

  return (
    <div className="my-6 rounded-lg overflow-hidden border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-[#0d1117] shadow-sm max-w-full">
      {/* Code Header */}
      <div
        className="flex items-center justify-between px-4 py-2 bg-zinc-100 dark:bg-[#161b22] border-b border-zinc-200 dark:border-zinc-800 select-none cursor-pointer"
        onClick={() => setIsCollapsed(!isCollapsed)}
      >
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">
            {language}
          </span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2 py-1 rounded text-xs text-zinc-500 hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-800 transition-all active:scale-95"
            title="Copy code"
          >
            {isCopied ? <CheckIcon /> : <CopyIcon />}
            <span>{isCopied ? "Copied!" : "Copy"}</span>
          </button>
          <button
            className="p-1 text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 transition-colors"
            title={isCollapsed ? "Expand" : "Collapse"}
          >
            <ChevronDownIcon collapsed={isCollapsed} />
          </button>
        </div>
      </div>

      {/* Code Content */}
      <div
        className={`transition-all duration-300 ease-in-out ${isCollapsed ? "max-h-0 opacity-0" : "max-h-[2000px] opacity-100"}`}
      >
        <div className="relative w-full">
          <SyntaxHighlighter
            language={language}
            style={isDark ? vscDarkPlus : vs}
            customStyle={customStyle}
            wrapLines={true}
            PreTag="div"
            CodeTag="div"
          >
            {codeText}
          </SyntaxHighlighter>
        </div>
      </div>
    </div>
  );
};

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({
  content,
  isDark = false,
}) => {
  return (
    // Updated colors to Zinc (black-gray)
    // Removed 'prose' (Tailwind Typography) and added 'markdown-body' (GitHub Markdown CSS)
    <div className="markdown-body p-8 bg-white dark:bg-zinc-950 min-h-screen transition-colors duration-200 text-zinc-900 dark:text-zinc-100">
      <style>{`
        .markdown-body {
          background-color: transparent !important;
          font-family: inherit;
        }
        
        /* Ensure PreBlock scrolls horizontally */
        .markdown-body pre {
            white-space: pre;
            overflow-x: auto;
            background-color: transparent !important;
            border: none !important;
            padding: 0 !important;
            margin: 0 !important;
        }

        /* Dark mode overrides for markdown-body */
        .dark .markdown-body {
          color-scheme: dark;
          color: #e4e4e7; /* zinc-200 */
        }

        .dark .markdown-body h1,
        .dark .markdown-body h2,
        .dark .markdown-body h3,
        .dark .markdown-body h4,
        .dark .markdown-body h5,
        .dark .markdown-body h6 {
          color: #f4f4f5; /* zinc-100 */
          border-bottom-color: #3f3f46; /* zinc-700 */
        }

        .dark .markdown-body a {
          color: #60a5fa; /* blue-400 */
        }
        
        .dark .markdown-body blockquote {
          color: #a1a1aa; /* zinc-400 */
          border-left-color: #3f3f46;
        }
        
        .dark .markdown-body hr {
          background-color: #3f3f46;
          height: 1px;
        }
        
        /* Table overrides */
        .dark .markdown-body table tr {
          background-color: transparent;
          border-color: #3f3f46;
        }
        .dark .markdown-body table tr:nth-child(2n) {
          background-color: rgba(63, 63, 70, 0.2);
        }
        .dark .markdown-body table th,
        .dark .markdown-body table td {
          border-color: #3f3f46;
        }
        
        /* Inline code override */
        .dark .markdown-body code:not([class*="language-"]) {
          background-color: rgba(63, 63, 70, 0.4);
          color: #e4e4e7;
        }
      `}</style>
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
          pre: ({ children, ...props }) => <PreBlock {...props} isDark={isDark}>{children}</PreBlock>,
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
};
